---
#install apache2
- name: installation apache
  hosts: web
  remote_user: exploit
  become: yes
  become_method: sudo

  tasks:
    - name: install mariadbclient
      apt: name=mariadb-client

    - name: connexion au serveur de bdd
      command: mysql -u hawad -h 172.20.10.6 --password=toor

