---
#install mariadb
- name: install bd
  hosts: db
  remote_user: exploit
  become: yes
  become_method: sudo

  tasks:
  - name: install mysql
    apt:
     name: python-mysqldb
     state: present

  - name: install mariadb-server
    apt: 
     name: mariadb-server
     state: present

  - name: install mysql common
    apt:
     name: mysql-common
     state: present
 

  - name: install mysql php
    apt:
     name: php-mysql
     state: present

  - name: copie le fichier mysqld.cnf   
    copy: 
       src: 50-server.cnf
       dest: /etc/mysql/mariadb.conf.d/50-server.cnf

  - name: creation du fichier /root/.my.cnf 
    template:
        src: my.cnf
        dest: /root/.my.cnf
        owner: root
        mode: 0600


  - mysql_db:
     login_user: root
     login_password: Toor1234
     name: dbwordpress
     state: present

  - mysql_user:
     login_user: root
     login_password: Toor1234
     name: diallo
     host: 172.20.10.3
     password: toor
     priv: 'dbwordpress.*:ALL,GRANT'
     
  - name: appication des régles mysql
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 3306
      ctstate: NEW
      syn: match
      jump: ACCEPT
      comment: Accept new https connections.


  - name: unmask mariadb.service
    command: systemctl unmask mysql.service 
  - name: service restart 
    service:
     name: mariadb
     state: restarted
